name: Shuttle Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Start PostgreSQL
        run: |
          docker run --name postgres-test -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=test_db -p 5432:5432 -d postgres:15
          
      - name: Set TEST_DATABASE_URL
        run: echo "TEST_DATABASE_URL=postgres://postgres:postgres@localhost:5432/test_db" >> $GITHUB_ENV

      - uses: shuttle-hq/deploy-action@main
        with:
          name: "root"
          deploy-key: ${{ secrets.SHUTTLE_API_KEY }}
          secrets: |
            ROOT_SECRET = '${{ secrets.ROOT_SECRET }}'
