name: Shuttle Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: shuttle-hq/deploy-action@main
        with:
          name: "root"
          no-test: "true"
          deploy-key: ${{ secrets.SHUTTLE_API_KEY }}
          secrets: |
            ROOT_SECRET = '${{ secrets.ROOT_SECRET }}'
