name: shuttle-run
on: 
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  run-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run shuttle project locally. 
        uses: ivinjabraham/shuttle-run@v1.1
        with: 
          secrets: |
            ROOT_SECRET = '${{ secrets.ROOT_SECRET }}'
